- name: Deploy Kubernetes Application via Ansible
  hosts: all
  become: true
  tasks:
    - name: Install the community.kubernetes collection
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.kubernetes
      changed_when: false

    - name: Create a Kubernetes deployment
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: health-deployment
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: health
            template:
              metadata:
                labels:
                  app: health
              spec:
                containers:
                - name: banking
                  image: mohankumar12/health-care
                  ports:
                  - containerPort: 8082

    - name: Create a Kubernetes service
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: health-service
          spec:
            selector:
              app: banking
            ports:
            - protocol: TCP
              port: 9090
              targetPort: 8082
              nodePort: 30084  # NodePort value (must be within 30000-32767)
            type: NodePort
