- name: Deploy Health Care App
  hosts: all
  become: true
  tasks:

    - name: Ensure Jenkins workspace directory exists
      file:
        path: "/var/lib/jenkins/workspace/health_care"
        state: directory
        mode: '0755'

    - name: Copy Kubernetes Deployment file to Jenkins workspace
      copy:
        dest: "/var/lib/jenkins/workspace/health_care/health-deployment.yml"
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: health-app
            labels:
              app: health
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: health
            template:
              metadata:
                labels:
                  app: health
              spec:
                containers:
                - name: health
                  image: mohankumar12/health-care
                  ports:
                  - containerPort: 8082

    - name: Apply Kubernetes Deployment
      command: kubectl apply -f /var/lib/jenkins/workspace/health_care/health-deployment.yml --validate=false

