- name: Setup Kubernetes Worker Node
  hosts: all
  become: true
  tasks:

    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - curl
          - ca-certificates
          - gnupg
        state: present

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present

    - name: Ensure br_netfilter module is loaded on boot
      lineinfile:
        path: /etc/modules-load.d/k8s.conf
        line: "br_netfilter"
        create: yes

    - name: Enable bridge-nf-call-iptables and IPv4 forwarding
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables=1
          net.ipv4.ip_forward=1

    - name: Apply sysctl settings
      command: sysctl --system

    - name: Restart networking service
      systemd:
        name: systemd-networkd
        state: restarted

    - name: Disable swap (required for Kubernetes)
      command: swapoff -a

    - name: Remove swap entry from /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^.*\sswap\s.*$'
        replace: '# swap disabled'

    - name: Install Docker
      shell: |
        curl -fsSL https://get.docker.com | sh
      args:
        executable: /bin/bash

    - name: Enable and start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install CRI-Dockerd
      get_url:
        url: https://raw.githubusercontent.com/lerndevops/labs/master/scripts/installCRIDockerd.sh
        dest: /tmp/installCRIDockerd.sh
        mode: '0755'

    - name: Execute CRI-Dockerd installation script
      command: bash /tmp/installCRIDockerd.sh

    - name: Ensure CRI-Dockerd service is running
      systemd:
        name: cri-docker
        state: started
        enabled: yes

    - name: Install Kubernetes components
      get_url:
        url: https://raw.githubusercontent.com/lerndevops/labs/master/scripts/installK8S.sh
        dest: /tmp/installK8S.sh
        mode: '0755'

    - name: Execute Kubernetes installation script
      command: bash /tmp/installK8S.sh

    - name: Ensure br_netfilter is loaded before joining the cluster
      shell: |
        modprobe br_netfilter
        echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables
        sysctl --system
      become: true

    - name: Join worker node to Kubernetes cluster
      command: > 
        kubeadm join 172.31.2.230:6443 
        --cri-socket unix:///var/run/cri-dockerd.sock 
        --token jk5f5e.gltqo6484agopt3b 
        --discovery-token-ca-cert-hash sha256:926b6bdd51dfff6549c7f21045eb1ee6707ba6d67b4f07f61ab40d67a453038d
      become: true
      ignore_errors: yes 
