---
- name: Install Kubernetes Worker Node with Docker
  hosts: all
  become: true
  tasks:

    # Update system packages
    - name: Update apt packages
      apt:
        update_cache: yes

    # Install required dependencies
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - curl
          - ca-certificates
          - gnupg
        state: present

    # Add Docker GPG key
    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    # Add Docker repository
    - name: Add Docker repository
      shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list

    # Install Docker
    - name: Install Docker
      apt:
        name:
          - docker.io
        state: present

    # Enable and start Docker service
    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    # Ensure Kubernetes GPG Key exists
    - name: Add Kubernetes GPG Key
      shell: |
        sudo mkdir -p -m 755 /etc/apt/keyrings
        curl -fsSLo /etc/apt/keyrings/kubernetes-apt-keyring.gpg https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key

    # Add Kubernetes repository
    - name: Add Kubernetes repository
      shell: |
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

    # Update apt cache again
    - name: Update apt cache
      apt:
        update_cache: yes

    # Install Kubernetes packages
    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    # Disable swap for Kubernetes
    - name: Disable swap
      shell: |
        swapoff -a
        sed -i '/ swap / s/^/#/' /etc/fstab

    # Get Join Command from Master (Run this only on the master first and copy the command)
    - name: Join Worker Node to Kubernetes Cluster
      shell: "<PASTE_YOUR_JOIN_COMMAND_HERE>"
      when: "'master' not in group_names"

    # Ensure kubelet is enabled
    - name: Enable kubelet service
      systemd:
        name: kubelet
        enabled: yes
        state: started
