---
- name: Kubernetes Cluster Setup and Deployment
  hosts: all
  become: true
  tasks:

    - name: Install required packages
      package:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present

    - name: Load the necessary kernel module for bridge networking
      shell: "modprobe br_netfilter"
      ignore_errors: true

    - name: Ensure bridge networking sysctl settings are enabled
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1
      notify: Apply sysctl changes

    - name: Apply sysctl changes
      command: sysctl --system

    - name: Disable swap
      command: swapoff -a

    - name: Remove swap entry from fstab
      replace:
        path: /etc/fstab
        regexp: '.*swap.*'
        replace: ''
    
    - name: Ensure required directories exist
      file:
        path: /etc/kubernetes
        state: directory
        mode: '0755'

    - name: Install kubeadm, kubelet, and kubectl
      shell: |
        curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        add-apt-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
        apt update && apt install -y kubelet kubeadm kubectl
      args:
        warn: false
      ignore_errors: true

    - name: Join the worker node to the Kubernetes cluster
      command: kubeadm join 172.31.2.230:6443 --cri-socket unix:///var/run/cri-dockerd.sock --token jk5f5e.gltqo6484agopt3b --discovery-token-ca-cert-hash sha256:926b6bdd51dfff6549c7f21045eb1ee6707ba6d67b4f07f61ab40d67a453038d
      register: kubeadm_join
      failed_when: "'[ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]' in kubeadm_join.stderr"
      ignore_errors: true

    - name: Verify kubelet is running
      systemd:
        name: kubelet
        state: started
        enabled: yes

    - name: Wait for Kubernetes API to be reachable
      retries: 10
      delay: 5
      command: kubectl get nodes
      register: kubectl_status
      until: kubectl_status.rc == 0
      ignore_errors: true

    - name: Copy kubeconfig to root
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        mode: '0600'

    - name: Deploy the health-care application
      command: kubectl apply -f /var/lib/jenkins/workspace/health_care/health-deployment.yml --validate=false
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: deployment_status
      retries: 5
      delay: 10
      until: deployment_status.rc == 0
      ignore_errors: true

  handlers:
    - name: Apply sysctl changes
      command: sysctl --system
